// Generated by https://quicktype.io

export interface ItemsResponseInteface {
  author: Author
  categories: string[]
  items: ItemResponse[]
}

export interface Author {
  name: string
  lastname: string
}

export interface ItemResponse {
  id: string
  title: string
  price: Price
  picture: string
  condition: string
  free_shipping: boolean
  addres: string
}

export interface Price {
  currency: string
  amount: number
  decimals: number
}
