// Generated by https://quicktype.io

export interface ItemDetailInterface {
  author: AuthorRes
  item: Item
}

export interface AuthorRes {
  name: string
  lastname: string
}

export interface Item {
  id: string
  title: string
  price: PriceRes
  picture: string
  condition: string
  free_shipping: boolean
  sold_quantity: number
  description: string
}

export interface PriceRes {
  currency: string
  aumount: number
  decimals: number
}
